.TH MPEGDEMUX 1 "2003-03-06" "mpegdemux" "HH"

.SH NAME
mpegdemux \- MPEG1/2 system stream demultiplexer

.SH SYNOPSIS
.BR mpegdemux " [options] [input [output]]"

.BR mpegdemux " --help"

.BR mpegdemux " --version"

.SH DESCRIPTION

.B mpegdemux
is an MPEG1/MPEG2 system stream demultiplexer. It can be
used to list the contents of an MPEG system stream and to extract
elementary streams.
.
.B mpegdemux
has three primary modes of operation:
.TP
list
In this mode the contents of an MPEG system stream are listed
in a textual form. This is useful to get an overview of what's in
an MPEG file
.TP
demux
In this mode elementary streams are extracted from an MPEG
system stream. The system stream packet structure is dissolved in
the process. Typically each extracted stream is written to its
own file.
.TP
remux
This is like demux, except that the MPEG system stream
structure is left intact. This means that the output is again
an MPEG system stream with all but the selected elementary
streams removed.

.SS OPTIONS

.TP
.I --help
Print usage information
.TP
.I --version
Print version information
.TP
.I -l, --list
List the system headers, packs and packets in an MPEG system stream.
.TP
.I -d, --demux
Demultiplex an MPEG system stream. The demultiplexed streams are
written to the output file unless the
.I --base-name
option is used. If the
.I --base-name
option is not used, only one stream can be demultiplexed (if more
streams are specified, they will be randomly interleaved in the
output file).
.TP
.I -r, --remux
Remultiplex an MPEG system stream. The output MPEG system stream
is written to the output file. Many options control what is
copied from the input to the output and what is discarded.
.TP
.I -s, --streams spec
This option selects streams.
.I
spec
specifies the stream ID's in the following form:

[+|-]<id>[-<id>]{/[+|-]<id>[-<id>]}

where id is either a stream ID or one of
.B all
or
.B none.
A - in front of an ID range means exclusion. For example the spec

-s 0xc0-0xcf/-0xc2

select all video streams (0xc0 - 0xcf) except stream 0xc2.
.TP
.I -p, --substream spec
This option selects private substreams. Whenever Private Stream 1
(0xbd) is selected using
.I -s,
the substreams within that private stream can be selected using
.I -p.
The syntax for spec is the same as for
.I -s.
.TP
.I -b, --base-name name
When demultiplexing more than one stream, the output file names
can be set using this option. To generate the output file name
for a stream, every # character in name is replaced by
a hex digit of the stream id. For example, to extract all
video streams in one go, use something like

$ mpegdemux -d -b video_##.m1v -s 0xc0-0xcf src.mpg

to get files video_c0.m1v, video-c1.m1v, ...
.TP
.I -f, --first
Process only the first occurrence of system headers, packs
and packets. Though this options also works for remuxing and
demuxing, it is most useful when listing. When this option
is used together with the
.I --list
option, only the first packet of each elementary stream will
be listed.
.TP
.I -h, --one-system-header
Ignore all system headers but the first.
.TP
.I -k, --one-pack
Ignore all packs but the first. This option is really useless.
.TP
.I -e, --one-end
When remuxing, make sure that the output MPEG system stream
has exactly one end code at the end.
.TP
.I -P, --empty-packs
When streams are removed during remuxing, packs can become
empty. Including these empty packs in the output is pointless
and therefore is not done by default. Use this option to
force inclusion of all packs.
.TP
.I -a, --ac3
AC3 sound packets in DVD MPEG2 streams have a 3 byte header
that is neither part of the MPEG specification nor of the
AC3 specification. When this option is used, these 3 bytes
are removed to produce a correct AC3 stream.
.TP
.I -u, --spu
This option is used to extract DVD subtitles. It is necessary
because the subtitle streams on DVD don't contain all the
timing information (the time stamps in the packet headers
are required). If this option is used during demultiplexing,
the output file is written in the following format:

"SPU " (4 bytes)

PTS (8 bytes, MSB first)
.br
SPU packet

PTS (8 bytes)
.br
SPU packet

and so on

.SH EXAMPLES

Get an overview of the elementary streams contained in an MPEG
system stream:

$ mpegdemux -l -f -s all -p all src.mpg


Extract the first video stream:

$ mpegdemux -d -s 0xe0 src.mpg dst.m1v


Extract all audio streams:

$ mpegdemux -d -s 0xc0-0xdf src.mpg dst.mpg


Remove the second video stream:

$ mpegdemux -r -s all/-0xc1 -p all src.mpg dst.mpg


Extract the first AC3 audio stream from a DVD MPEG2 system stream:

$ mpegdemux -d -s 0xbd -p 0x80 --ac3 src.mpg dst.ac3

.SH SEE ALSO
.BR mplex "(1)"

.SH AUTHOR
Hampa Hug <hampa@hampa.ch>
