.TH MPEGDEMUX 1 "2003-02-02" "mpegdemux" "HH"

.SH NAME
mpegdemux \- Demultiplex MPEG1 system streams

.SH SYNOPSIS
.BR mpegdemux " [options]"

.BR mpegdemux " --help"

.BR mpegdemux " --version"

.SH DESCRIPTION

.SS OPTIONS

.TP
.I --help
Print usage information

.TP
.I --version
Print version information

.SH SEE ALSO
.BR mplex "(1)"

.SH AUTHOR
Hampa Hug <hampa@hampa.ch>
